services:
  db:
    image: postgres:15
    container_name: tg_scrap_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tg_scrap
      POSTGRES_PASSWORD: tg_scrap
      POSTGRES_DB: tg_scrap
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./telegram_scraper/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  parser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_scrap_parser
    command: ["poetry", "run", "python", "-m", "telegram_scraper.main"]
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /app

volumes:
  pgdata:
